#!/bin/sh

set -e

echo "Hey, if you are not David, please don't run this. Press enter to begin."

read

BUBBEL_CODEGEN="" cargo r

git clone https://github.com/davnotdev/bubbel-android /tmp/bubbel-android
git clone https://github.com/davnotdev/bubbel-ios /tmp/bubbel-ios
git clone https://github.com/davnotdev/bubbel /tmp/bubbel

DIR=$(dirname $0)

cp $DIR/BubbelBackend.kt /tmp/bubbel-android/app/src/main/java/com/example/bubbel/model/backend.kt
cp $DIR/BubbelBackend.swift /tmp/bubbel-ios/bubbel/Backend.swift
cp $DIR/bubbelBackend.ts /tmp/bubbel/lib/bubbelBackend.ts


cd /tmp/bubbel-android/
git add .
git commit -m "Update backend files. (auto)" || echo
git push

cd /tmp/bubbel-ios/
git add .
git commit -m "Update backend files. (auto)" || echo
git push

cd /tmp/bubbel/
git add .
git commit -m "Update backend files. (auto)" || echo
git push

rm -rf /tmp/bubbel
rm -rf /tmp/bubbel-ios
rm -rf /tmp/bubbel-android

